platform :ios, '9.0'
use_frameworks!

target 'Japx_Example' do
  pod 'Japx/Objc', :path => '../'
  pod 'Japx/RxCodableMoya', :path => '../'

  target 'Japx_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
