platform :ios, '9.0'
use_frameworks!

target 'Japx_Example' do
  pod 'Japx/RxCodableMoya', :path => '../'

  target 'Japx_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
