update_fastlane
default_platform :ios

platform :ios do

    before_all do
      setup_circle_ci
    end
  
    lane :unit_tests do
      scan(workspace: "./Example/Japi.xcworkspace", scheme: "Japi_Example")
    end
  
    after_all do |lane|
    end
  
    error do |lane, exception|
    end
  
  end
  